### PR TITLE
feat(config): Add auto line endings normalization

### LINKED ISSUE #10: Add .gitattributes file
Atteding to @Jefferson227 [comment](https://github.com/ifactory-solutions/inside-client/pull/8#pullrequestreview-64294435) on #8, the end-of-line normalization should be handled with `.gitattributes` file. Setting `* text=auto`  as default behavior to automatically normalize line endings, which is mentioned on [git docs](https://git-scm.com/docs/gitattributes#gitattributes-Settostringvalueauto).

### PR DESCRIPTION
**Pull request by paulonotz0r**
Add `.gitattributes` file which automatically normalize line endings 
with `* text=auto` attribute behavior.

Closes #10

### CODE REVIEW

**Comment by jouderianjr** [comment]
I think this is not setting an universal end of line, still seems everyone can use `lf` and `crlf`. 

Using this [docs](https://help.github.com/articles/dealing-with-line-endings/) as reference I believe we need to set something like `text eol=lf`, however we could handle that in editor config  (#12) as well, could be better take care of this type of configuration only in one place, What do you think about?

😄

**Comment by paulonotz0r** [comment]
In the `.gitattributes` case, setting `text=auto`, Git will handle line endings automatically for each OS/enviroment. But I really like the #12 approach and I agree it's better.

I will close this PR and follow #12 suggestion.

**Comment by jvcjunior** [comment]
Hey @paulonotz0r great job!! Don't give up! The #12 is open, feel free to get if you want! ;)

**Comment by paulonotz0r** [comment]
Thanks, @jvcjunior! Actually I've learned a new thing about `.editorconfig` and that give me motivation to go further in this project. :D

**Pull request closed without merging**
