### PR TITLE
feat(lint): add commit lint

### PR DESCRIPTION
**Pull request by jvcjunior**
- Checks if the commit message is meeting project standards
- Checks there's no eslint error/warning on the commited files

issue: #4

### CODE REVIEW

**Review by yannbf — APPROVED** [review]
Awesome! Tested it and it works great.
What I suggest though is to add the rules to WIKI in order to make it accessible to anyone that doesn't know about it.

It would be great if, in case of commit error, the output message was something like:
_In case you don't know the commit rules of this project, please refer to https://github.com/ifactory-solutions/wiki-url-with-commit-rules_.

**Comment by paulonotz0r** [comment]
Nice! Works like a charm when I've tested it!

**Review by paulonotz0r — APPROVED** [review]

**Review by Jefferson227 — APPROVED** [review]
It worked very well on Linux, but if you are using Windows you must attempt to the "End of Line Sequence" configuration which must be LR instead of CRLF (I believe it's a subject for another issue).

And I agree with @yannbf regarding to put a link to a WIKI just to provide some orientation about our commit message standards for those who want to contribute to the project.

**Comment by wellyal** [comment]
Awesome, seems to work well congrats :)

**Review by wellyal — APPROVED** [review]
Awesome, seems to work well congrats :)

**Pull request merged**
